name: nfitness
description: "An alternative client for eFitness"

publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  crypto: ^3.0.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.4.0
  intl: ^0.20.2
  logging: ^1.3.0
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
